sudo: true 
cache: pip

addons:
  apt:
    packages:
      - python-openpyxl   

language: python

python:
  - "2.7"

env:
  - VERSION="9.0" LINT_CHECK="1"
  - VERSION="9.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="9.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - pip install openpyxl 
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}

script:
  - travis_run_tests ${VERSION}

after_success:
  coveralls
