[project]
name = "odoo-addons-oca-stock-logistics-reporting"
version = "19.0.20260317.0"
dependencies = [
    "odoo-addon-stock_picking_report_external_note==19.0.*",
    "odoo-addon-stock_move_delay_report==19.0.*",
    "odoo-addon-stock_picking_report_valued==19.0.*",
    "odoo-addon-stock_product_demand_info==19.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 19.0",
]
